### PR TITLE
Add compatibility to Portenta H7

### PR DESCRIPTION
**Pull request by facchinm**

### CODE REVIEW

**Comment by per1234** [comment]
Fixes https://github.com/arduino-libraries/ArduinoMotorCarrier/issues/40
Supersedes https://github.com/arduino-libraries/ArduinoMotorCarrier/pull/39

**Comment by facchinm** [comment]
I don't know why the CI keeps failing but if I compile locally it's ok... :thinking:

**Review by per1234 — CHANGES_REQUESTED** [review]
Please add `mbed_portenta` and `mbed` to the `architectures` field of `library.properties` .

**Comment by per1234** [comment]
>I don't know why the CI keeps failing but if I compile locally it's ok..

Are you referring to this failure @facchinm?
https://github.com/arduino-libraries/ArduinoMotorCarrier/runs/4093746348?check_suite_focus=true#step:3:72
```
  /home/runner/work/ArduinoMotorCarrier/ArduinoMotorCarrier/examples/Flasher/Flasher.ino:115:25: error: call of overloaded 'write(uint32_t)' is ambiguous
     Wire.write((uint32_t)0);
                           ^
```

**Comment by facchinm** [comment]
@per1234 really this one :slightly_smiling_face:  https://github.com/arduino-libraries/ArduinoMotorCarrier/runs/4093746348?check_suite_focus=true#step:3:118

**Comment by per1234** [comment]
I apologize for the confusion @facchinm. This is the result of my poor design of the log output from the `arduino/compile-sketches` action. I need to make some time to work on that ([HWCI-234](https://arduino.atlassian.net/browse/HWCI-234)).

From https://github.com/arduino-libraries/ArduinoMotorCarrier/runs/4093746348?check_suite_focus=true#step:3:113
```
Compiling previous version of sketch to determine memory usage change
```
So this failure was from when the action checked out the base ref of this PR (`master` branch) to do a second compilation to determine the size deltas. That failure is expected.

You can see here that the compilation from when the head ref of this PR (`portenta_compatibility` branch) was checked out was successful:
https://github.com/arduino-libraries/ArduinoMotorCarrier/runs/4093746348?check_suite_focus=true#step:3:109

The compilations of the base ref are done solely for data collection purposes. Their result does not affect the status of the CI, but only the informational size deltas report comment. The only reason the Portenta H7 compilation job failed was [the error that occurred during the "Flasher" example compilation](https://github.com/arduino-libraries/ArduinoMotorCarrier/runs/4093746348?check_suite_focus=true#step:3:72). If that error was resolved or the CI workflow reconfigured to skip that example, the job would pass ✔️

**Comment by facchinm** [comment]
Ahhhnn got it :smile: (you probably told me 1000 times but I still end up forgetting this information :stuck_out_tongue_closed_eyes: )
The `Wire.write(0)` ambiguity should be fixed at API level, so I'd leave the "offending code" here and create the specific issue in the proper (core or api) repo

**Pull request merged**
